from django.urls import path
import farmland1.views

urlpatterns = [
    path('',farmland1.views.home, name='home'),
    path('home', farmland1.views.home, name='home'),
    path('about',farmland1.views.about, name='about'),
    path('blog', farmland1.views.blog, name='blog'),
    path('contact', farmland1.views.contact, name='contact'),
    path('services', farmland1.views.services, name='services'),
    path('testimonials', farmland1.views.testimonials, name='testimonials'),
    path('admin', farmland1.views.admin, name='admin'),
    path('worker', farmland1.views.worker, name='worker'),
    path('blogcarousel', farmland1.views.blogcarousel, name='blogcarousel'),
    path('agricultureprd', farmland1.views.agricultureprd, name='agricultureprd'),
    path('blogcarousel', farmland1.views.blogcarousel, name='blogcarousel'),
    path('blogsidebar', farmland1.views.blogsidebar, name='blogsidebar'),
    path('cart', farmland1.views.cart, name='cart'),
    path('checkout', farmland1.views.checkout, name='checkout'),
    path('diaryproducts', farmland1.views.diaryproducts, name='diaryproducts'),
    path('faq', farmland1.views.faq, name='faq'),
    path('farmers', farmland1.views.farmers, name='farmers'),
    path('farmerscarousel', farmland1.views.farmerscarousel, name='farmerscarousel'),
    path('freshvegetables', farmland1.views.freshvegetables, name='freshvegetables'),
    path('organicproducts', farmland1.views.organicproducts, name='organicproducts'),
    path('productdetails', farmland1.views.productdetails, name='productdetails'),
    path('products', farmland1.views.products, name='products'),
    path('project1', farmland1.views.project1, name='project1'),
    path('project2', farmland1.views.project2, name='project2'),
    path('projectcarousel', farmland1.views.projectcarousel, name='projectcarousel'),
    path('projectdetails', farmland1.views.projectdetails, name='projectdetails'),
    path('servicescarousel', farmland1.views.servicescarousel, name='servicescarousel'),
    path('testimonialscarousel', farmland1.views.testimonialscarousel, name='testimonialscarousel'),
    path('blogdetails', farmland1.views.blogdetails, name='blogdetails'),
    path('registration', farmland1.views.registration, name='registration'),
    path('registrationworker', farmland1.views.registrationworker, name='registrationworker'),
    path('registrationstaff', farmland1.views.registrationstaff, name='registrationstaff'),
    path('login', farmland1.views.login, name='login'),
    path('userhome', farmland1.views.userhome, name='userhome'),
    path('staffhome', farmland1.views.staffhome, name='staffhome'),
    path('adminhome', farmland1.views.adminhome, name='adminhome'),
    path('workerhome', farmland1.views.workerhome, name='workerhome'),
    path('logout', farmland1.views.logout, name='logout'),
    path('schedule_work', farmland1.views.schedule_work, name='schedule_work'),
    path('work_schedule', farmland1.views.work_schedule, name='work_schedule'),

]


