# Generated by Django 4.1.3 on 2022-12-28 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farmland1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='About_website',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='First_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Image',
            field=models.ImageField(null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Last_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Password',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Registration_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='User_role',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Schedule_worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=200, null=True)),
                ('work_reg', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmland1.registration')),
            ],
        ),
    ]
